

DROP TABLE CF_DECLARATION;
DROP TABLE APPROVALS;
DROP TABLE LEAD;
DROP TABLE PROPRITOR;
DROP TABLE BUSINESS_ENTITY;
DROP TABLE ACCOUNT_INFO;
DROP TABLE BANK_STATEMENT;
DROP TABLE FUNDING_DETAIL;
DROP TABLE BANK_USE;
		 
CREATE TABLE PROPRITOR	(
	PROPRITOR_ID 			NUMBER(10) NOT NULL, 
	SALUATATION 			VARCHAR(3),
	FIRST_NAME 				VARCHAR(30),
	MIDDLE_NAME 			VARCHAR(30),
	LAST_NAME 				VARCHAR(30),
	MAIDEN_NAME 			VARCHAR(30),
	GENDER 					VARCHAR(1),
	BIRTH_DATE 				DATE,
	FATHER_NAME 			VARCHAR(30),
	MOTHER_NAME 			VARCHAR(30),
	NATIONALITY 			VARCHAR(40),
	BIRTH_COUNTRY 			VARCHAR(40),
	TAX_COUNTRY 			VARCHAR(40),
	ADDR_LINE_1 			VARCHAR(40),
	ADDR_LINE_2 			VARCHAR(40),
	ADDR_LINE_3 			VARCHAR(40),
	LAND_MARK 				VARCHAR(40),
	PIN_CODE 				VARCHAR(6),
	STATE 					VARCHAR(40),
	PHONE_NO 				VARCHAR(10),
	EMAIL 					VARCHAR(40),
	PHOTO_DOC_ID 			VARCHAR(40),
	PAN_NO 					VARCHAR(10),
	PAN_STATUS 				VARCHAR(1),
	PAN_DOC_DMSID 			VARCHAR(40),
	PAN_VER_DIGILOCKER 		NUMBER(1),
	PAN_VER_FINTECH 		NUMBER(1),
	KYC_DOC_TYPE 			VARCHAR(40),
	KYC_DOC_ID 				VARCHAR(40),
	KYC_DOC_DMSID 			VARCHAR(40),
	KYC_DOC_VER_DIGILOCKER 	NUMBER(1),
	KYC_DOC_VER_FINTECH 	NUMBER(1),
	NAME_MISS_PROOF_DMSID 	VARCHAR(40),
    CONSTRAINT PROPRITOR_ID_PK PRIMARY KEY(PROPRITOR_ID)
);

CREATE TABLE BUSINESS_ENTITY	(
	BUSINESS_ENTITY_ID 		NUMBER(10) NOT NULL,
	NAME 					VARCHAR(40),
	ACCOUNT_TITLE			VARCHAR(40),
	INCORPORATION_DATE		DATE,
	INDUSTRY_NATURE			VARCHAR(40),
	BUSINESS_LINE			VARCHAR(40),
	TURNOVER				VARCHAR(40),
	INT_TRADE_TURNOVER 		VARCHAR(40),
	IEC_CODE 				VARCHAR(40),
	ADDR_LINE_1 			VARCHAR(40),
	ADDR_LINE_2 			VARCHAR(40),
	ADDR_LINE_3 			VARCHAR(40),
	LANDMARK 				VARCHAR(40),
	PINCODE 				VARCHAR(6),
	STATE 					VARCHAR(40),
	PHONE_NO 				VARCHAR(10),
	EMAIL 					VARCHAR(40),
	COMM_ADDR_LINE_1 		VARCHAR(40),
	COMM_ADDR_LINE_2 		VARCHAR(40),
	COMM_ADDR_LINE_3 		VARCHAR(40),
	COMM_LANDMARK 			VARCHAR(40),
	COMM_PINCODE 			VARCHAR(6),
	COMM_STATE 				VARCHAR(40),
	COMM_PHONE_NO 			VARCHAR(10),
	ENT_PRI_DOCID 			VARCHAR(40),
	BIS_PRI_DOC_DMSID 		VARCHAR(40),
	BIS_SEC_DOC_TYPE 		VARCHAR(40),
	BIS_LINE_PRF_DMSID 		VARCHAR(40),
	COMM_ADDR_PRF_DMSID 	VARCHAR(40),
	CONSTRAINT BUSINESS_ENTITY_ID_PK PRIMARY KEY(BUSINESS_ENTITY_ID)
);

CREATE TABLE ACCOUNT_INFO (
	ACCOUNT_INFO_ID 	NUMBER(10) NOT NULL,
	OPERN_MODE 			VARCHAR(40),
	NO_OF_SIGNTRY		NUMBER(10),
	NO_OF_CHEQUES		NUMBER(10),
	DEBIT_CARD			NUMBER(1,0),
	EMAIL_STMT			NUMBER(1,0),
	SMS_ALERT			NUMBER(1,0),
	DS_BNK				NUMBER(1,0),
	DS_BNK_CNT_PERSON	VARCHAR(40),
	DS_BNK_MONILE_NO	VARCHAR(10),
	NAME_ON_CARD 		VARCHAR(40),
	BRANCH_NAME			VARCHAR(40),
	BRANCH_CODE			VARCHAR(10),
	NOMINEE				VARCHAR(40),
	NOMINEE_NAME		VARCHAR(40),
	NOMINEE_ADDR		VARCHAR(40),
	NOMINEE_RELN		VARCHAR(40),
	NOMINEE_DOB 		DATE,
	CONSTRAINT ACCOUNT_INFO_ID_PK PRIMARY KEY(ACCOUNT_INFO_ID)
);

CREATE TABLE BANK_STATEMENT	(
	BANK_STMT_ID	NUMBER(10) NOT NULL,
	ACCOUNT_NO 		VARCHAR(40),
	ADDRESS			VARCHAR(40),
	STMT_FROM_DATE	DATE,
	STMT_TO_DATE	DATE,
	STMT_DURATION	NUMBER(10),
	STATUS			VARCHAR(40),
	IS_NEG_CLOSING_BALANCE NUMBER(1,0),
	DMSID 			VARCHAR(40),
	CONSTRAINT BANK_STMT_ID_PK PRIMARY KEY(BANK_STMT_ID)
);

CREATE TABLE FUNDING_DETAIL	(
	FUNDING_ID 		NUMBER(10) NOT NULL,
	CHEQUE_NO		VARCHAR(10),
	BANK_NAME		VARCHAR(40),
	BRANCH_IFSC		VARCHAR(10),
	AMOUNT			NUMBER(12,2),
	CONSTRAINT FUNDING_DETAIL_PK PRIMARY KEY(FUNDING_ID)
);

CREATE TABLE LEAD (
	LEAD_ID 			NUMBER(10) NOT NULL, 
	LEAD_REF_ID			VARCHAR(10),
	SFDC_CASE_ID 		VARCHAR(10),
	PROPRITOR_ID 		NUMBER(10),
	BUSINESS_ENTITY_ID 	NUMBER(10),
	STATUS 				VARCHAR(40),
	STAGE				VARCHAR(40),
	CURR_DATE 			DATE,
	LEAD_CONVERTOR 		VARCHAR(40),
	CREATED_DATE 		DATE,
	BANK_STMT_ID 		NUMBER(10),
	CREDIT_EXPOSURE 	NUMBER(10),
	DISPUTE_ID 			NUMBER(10),
	NOC_DOC_DMSID 		VARCHAR(40),
	MOBILE_NO_EXISTS 	NUMBER(1),
	MOBILE_NO_EXISTS_REASON VARCHAR(40),
	PRODUCT 			VARCHAR(40),
	ACCOUNT_INFO_ID 	NUMBER(10),
	FUNDING_ID 			NUMBER(10),
	BANK_USE_ID			NUMBER(10),
	TRADE_PLANTFORM 	NUMBER(1),
	CUST_INFO_FROM_DMSID VARCHAR(40),
	BARCODE 			VARCHAR(40),
	MITC_DMS_ID			VARCHAR(10),
	SITE_VER_STATUS 	VARCHAR(40),
	SIT_VER_DATE 		DATE,
	SITE_VER_PHOTO_DMSID VARCHAR(40),
    CONSTRAINT LEAD_ID_PK PRIMARY KEY(LEAD_ID),
    CONSTRAINT PROPRITOR_ID_FK FOREIGN KEY(PROPRITOR_ID) REFERENCES PROPRITOR(PROPRITOR_ID),
    CONSTRAINT BUSINESS_ENTITY_ID_FK FOREIGN KEY(BUSINESS_ENTITY_ID) REFERENCES BUSINESS_ENTITY(BUSINESS_ENTITY_ID),
    CONSTRAINT BANK_STMT_ID_FK FOREIGN KEY(BANK_STMT_ID) REFERENCES BANK_STATEMENT(BANK_STMT_ID),
    CONSTRAINT ACCOUNT_INFO_ID_FK FOREIGN KEY(ACCOUNT_INFO_ID) REFERENCES ACCOUNT_INFO(ACCOUNT_INFO_ID),
    CONSTRAINT FUNDING_ID_FK FOREIGN KEY(FUNDING_ID) REFERENCES FUNDING_DETAIL(FUNDING_ID),
	CONSTRAINT BANK_USE_ID_FK FOREIGN KEY(BANK_USE_ID) REFERENCES BANK_USE(BANK_USE_ID)
);

CREATE TABLE CF_DECLARATION	(
	CF_DECL_ID		NUMBER(10) NOT NULL,
	BANK 			VARCHAR(40),
	BRANCH			VARCHAR(40),
	ACCT_NO			VARCHAR(20),
	FACILITY_TYPE	VARCHAR(10),
	AMOUNT			NUMBER(12,2),
	LEAD_ID			NUMBER(10),
	CONSTRAINT CF_DECLARATION_PK PRIMARY KEY(CF_DECL_ID),
	CONSTRAINT LEAD_ID_FK FOREIGN KEY(LEAD_ID) REFERENCES LEAD(LEAD_ID) 
);

CREATE TABLE APPROVALS	(
	APPROVAL_ID 		NUMBER(10) NOT NULL,
	APPROVAL_NAME		VARCHAR(30),
	APPROVER_NAME		VARCHAR(30),
	APPROVAL_PRF_DMSID	VARCHAR(40),
	LEAD_ID				NUMBER(10),
	CONSTRAINT APPROVALS_PK PRIMARY KEY(APPROVAL_ID),
	CONSTRAINT APP_LEAD_ID_FK FOREIGN KEY(LEAD_ID) REFERENCES LEAD(LEAD_ID)
);


CREATE TABLE BANK_USE (
	BANK_USE_ID			NUMBER(10) NOT NULL,
	CA_VARIANT_CD		VARCHAR(30),
	LEAD_GENERATOR		VARCHAR(30),
	LEAD_WARMER			VARCHAR(30),
	PROMO_CODE			VARCHAR(30),
	CAMPAIGN_CODE		VARCHAR(30),
	SITE_VER_CUST_ADDR	NUMBER(1),
	KYC_DOC_RTN_CUST	NUMBER(1),
	SIGNED_IN_PRESENCE	NUMBER(1),
	CONSTRAINT BANK_USE_PK PRIMARY KEY(BANK_USE_ID)
);